name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 6.14.5  # specify the pnpm version here

      - name: Verify pnpm version
        run: pnpm --version

      - name: Check for pnpm lock file
        run: |
          if [ -f pnpm-lock.yaml ]; then
            echo "pnpm-lock.yaml file exists."
          else
            echo "pnpm-lock.yaml file does not exist."
            exit 1
          fi

      - name: Install dependencies
        run: pnpm install

      - name: Build the site
        run: pnpm build

      - name: Verify build output
        run: ls -la dist

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure you have this secret set in your GitHub repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          pnpm deploy
